# Generated by Django 5.0.1 on 2024-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_delete_admin_alter_user_managers_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
