# Generated by Django 5.0.1 on 2024-01-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_loan_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrowed_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
